# update package list
sudo apt update
sudo apt upgrade -y

# install ddclient
sudo apt install ddclient

# configure ddclient
sudo nano /etc/ddclient.conf

cat <<EOF >> /etc/ddclient.conf
# Configuration file for ddclient generated by debconf
#
# /etc/ddclient.conf

protocol=namecheap
use=web, web=ipify-ipv4
server=dynamicdns.park-your-domain.com
login=andriynovykov.dev
password='7f16e6f793544f4eb38dc4b76425bd96'
homelab
EOF

# start service
sudo systemctl enable ddclient
sudo systemctl start ddclient
